import typer
from rich.console import Console
from rich.table import Table
from rich.text import Text
from rich import box
from clutch_cli.api import get_client

console = Console()


def insight():
    """Get your AI-generated weekly insight."""
    with get_client() as client:
        try:
            console.print()
            console.print("[dim]Generating insight...[/dim]")

            response = client.get("/insights/weekly")
            if response.status_code != 200:
                console.print("[red]Error: Failed to fetch insight.[/red]")
                raise typer.Exit(1)

            data = response.json()

            if "message" in data:
                console.print(f"[yellow]{data['message']}[/yellow]")
                raise typer.Exit()

            stats = data["stats"]
            summary = data["ai_summary"]

            console.print()
            console.rule("[bold blue]⚡ CLUTCH — WEEKLY INSIGHT[/bold blue]")
            console.print()

            # AI summary block
            console.print(f"[dim]Week of[/dim] [white]{data['week_start']}[/white]")
            console.print()
            console.print(Text(summary, style="white"), soft_wrap=True)
            console.print()
            console.rule(style="dim")
            console.print()

            # Stats row
            table = Table(box=box.SIMPLE, show_header=False, pad_edge=False)
            table.add_column("Label", style="dim", width=22)
            table.add_column("Value", style="bold white")

            table.add_row("Commits", f"[green]{stats['total_commits']}[/green]")
            table.add_row("Active Days", f"[green]{stats['active_days']}[/green]")
            table.add_row("Pull Requests", str(stats["total_prs"]))
            table.add_row("Issues", str(stats["total_issues"]))
            table.add_row("Best Day", str(stats["best_day"]))
            table.add_row("Generated by", f"[dim]{data['generated_by']}[/dim]")

            console.print(table)
            console.print()
            console.rule(style="dim")
            console.print()

        except Exception:
            console.print("[red]Error: Could not connect to Clutch API.[/red]")
            raise typer.Exit(1)
